provincias_codigos_postales = {
    "Buenos Aires": "1",
    "Catamarca": "4",
    "Chaco": "3",
    "Chubut": "9",
    "Córdoba": "5",
    "Corrientes": "3",
    "Entre Ríos": "3",
    "Formosa": "3",
    "Jujuy": "4",
    "La Pampa": "6",
    "La Rioja": "5",
    "Mendoza": "5",
    "Misiones": "3",
    "Neuquén": "8",
    "Río Negro": "8",
    "Salta": "4",
    "San Juan": "5",
    "San Luis": "5",
    "Santa Cruz": "9",
    "Santa Fe": "3",
    "Santiago del Estero": "4",
    "Tierra del Fuego": "9",
    "Tucumán": "4"
}
